add detail to README.md
asiniy/download pull request #1
Opened 2017-07-12 19:12 UTC by LTheGreats

2017-07-14 04:19 UTC, asiniy commented
@LTheGreats prooflink?

2017-07-14 15:30 UTC, LTheGreats commented
[Proof](https://github.com/phoenixframework/phoenix/blob/master/mix.exs)

2017-07-22 11:54 UTC, asiniy commented
@LTheGreats it's kinda strange proof. I asked for an article or release notes on elixir website

2017-07-26 02:57 UTC, LTheGreats commented
Here is release notes: [https://elixir-lang.org/blog/2017/01/05/elixir-v1-4-0-released/](https://elixir-lang.org/blog/2017/01/05/elixir-v1-4-0-released/)

2017-07-26 07:27 UTC, asiniy requested changes

2017-07-26 07:27 UTC, asiniy commented on README.md
> +Only in elixir 1.2 an below:
`1.3` and below :)

2017-07-26 07:39 UTC, asiniy commented on README.md
> +Only in elixir 1.2 an below:
@LTheGreats

2017-07-26 16:39 UTC, LTheGreats commented
Oops. That was a weird mistake.

2017-07-26 17:53 UTC, asiniy commented
@LTheGreats please make it in 1 commit and I'll merge

2017-08-06 12:29 UTC, asiniy commented
@LTheGreats ?

2017-08-08 02:03 UTC, grandafrato commented
I didn't have time to figure out how to squash the two git commits so I just forked the repo again and will make another pull request to solve this issue in only 1 commit.

2017-08-08 02:03 UTC, closed without merging